name: Node.js Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Vyberte si požadovanú verziu Node.js

    - name: Install npm dependencies
      run: npm install

    - name: Run your Node.js application
      run: npm start  # Nahraďte toto príkazom na spustenie vašej aplikácie
