name: Create Draft Release for Commits

on:
  push:
    branches: [main]

jobs:
  draft-release:
    if: startsWith(github.event.head_commit.message, 'rls:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Draft Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract version from commit message
        VERSION=$(echo "${{ github.event.head_commit.message }}" | head -n 1 | sed 's/^rls:\s*//')
        
        # Create draft release
        gh release create $VERSION \
          --draft \
          --title "$VERSION" \
          --notes "${{ github.event.head_commit.message }}"
