name: Create Draft Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write # Allows the workflow to create releases

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true # Creates the release as a draft
          generate_release_notes: true # Automatically generates release notes
