name: Create Draft Release for Commits

on:
  push:
    branches: [main]

jobs:
  draft-release:
    # Ensure the workflow only runs for commits starting with "rls:"
    if: startsWith(github.event.head_commit.message, 'rls:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Extract version from commit message
    - name: Extract Version
      id: extract-version
      run: |
        VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '^rls:\K[\w.-]+')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # Step 3: Create a draft release
    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.extract-version.outputs.version }}
        release_name: ${{ steps.extract-version.outputs.version }}
        draft: true
        generate_release_notes: true
