name: Black Code Formatter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your version

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: |
          black --check .
