name: Danger Python Bot

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          pip install danger-python

      # Install Node.js (Danger requires Node)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install Danger
      - name: Install Danger
        run: npm install --save-dev danger

      # Run Danger to perform the review
      - name: Run Danger
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
